# Generated by Django 4.1.2 on 2022-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='youtubeapi',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
