# Generated by Django 4.1.2 on 2022-11-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_channel_alter_youtubeapi_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
